#!/usr/bin/env python3
"""Merge all batch files in research/_batches/ into staging.json, deduplicating
by id, and generate sources.md indexed by id.

Validates:
  - Every entry has the required Entity fields.
  - Every entry has a _provenance with confidence in {A,B} and >=1 source URL.

Usage:
    python3 merge_batches.py
"""
import json
import sys
from pathlib import Path
from collections import OrderedDict, Counter

ROOT = Path(__file__).resolve().parents[1]  # research/
BATCH_DIR = ROOT / "_batches"
STAGING = ROOT / "staging.json"
SOURCES_MD = ROOT / "sources.md"

REQUIRED = {"id", "name", "company", "category", "imageUrl", "year", "isNew", "specs"}
VALID_CONF = {"A", "B"}

batches = sorted(BATCH_DIR.glob("batch_*.json"))
if not batches:
    print("no batch files", file=sys.stderr); sys.exit(1)

all_entries = OrderedDict()  # id -> entry
collisions = []
errors = []
per_batch_counts = []
for bf in batches:
    try:
        data = json.loads(bf.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        errors.append(f"PARSE FAIL {bf.name}: {e}")
        continue
    per_batch_counts.append((bf.name, len(data)))
    for entry in data:
        eid = entry.get("id", "<missing>")
        # validate required fields
        missing = REQUIRED - set(entry.keys())
        if missing:
            errors.append(f"{bf.name}:{eid}: missing fields {missing}")
            continue
        prov = entry.get("_provenance")
        if not prov:
            errors.append(f"{bf.name}:{eid}: missing _provenance")
            continue
        if prov.get("confidence") not in VALID_CONF:
            errors.append(f"{bf.name}:{eid}: bad confidence {prov.get('confidence')!r}")
            continue
        if not prov.get("sources"):
            errors.append(f"{bf.name}:{eid}: empty sources")
            continue
        if eid in all_entries:
            collisions.append(f"{bf.name}:{eid} (already from {all_entries[eid].get('_source_batch')})")
            # keep the first; do not overwrite
            continue
        entry["_source_batch"] = bf.name  # ephemeral; stripped on write
        all_entries[eid] = entry

# Strip _source_batch before writing
final = []
for e in all_entries.values():
    e2 = {k: v for k, v in e.items() if k != "_source_batch"}
    final.append(e2)

STAGING.write_text(json.dumps(final, ensure_ascii=False, indent=2), encoding="utf-8")

# ---- Generate sources.md ----
lines = []
lines.append("# Sources — per-entry citation index")
lines.append("")
lines.append("Generated by `_tools/merge_batches.py`. Do not hand-edit; modify the source batch files and re-run.")
lines.append("")
lines.append("Rule: every entry below has ≥1 A or B source. See `README.md` for tier definitions.")
lines.append("")
lines.append("---")
lines.append("")
lines.append("## Staging entries (auto-generated)")
lines.append("")

# group by category for readability
by_cat = {}
for e in final:
    by_cat.setdefault(e["category"], []).append(e)

for cat in sorted(by_cat):
    entries = sorted(by_cat[cat], key=lambda e: e["id"])
    lines.append(f"### {cat} ({len(entries)} entries)")
    lines.append("")
    for e in entries:
        prov = e["_provenance"]
        lines.append(f"#### `{e['id']}` — {e['name']} ({e.get('company','')})")
        lines.append("")
        lines.append(f"- **Confidence:** {prov['confidence']}")
        lines.append(f"- **Sources:**")
        for s in prov["sources"]:
            t = s.get("type","")
            ftype = f" — {t}" if t else ""
            ff = s.get("fetched","")
            lines.append(f"  - [{s.get('title','(no title)')}]({s['url']}){ftype}{' — fetched ' + ff if ff else ''}")
        fv = prov.get("fields_verified") or []
        if fv:
            lines.append(f"- **Fields verified:** {', '.join(fv)}")
        fu = prov.get("fields_uncertain") or []
        if fu:
            lines.append(f"- **Fields uncertain:** {', '.join(fu)}")
        notes = prov.get("notes","").strip()
        if notes:
            lines.append(f"- **Notes:** {notes}")
        lines.append("")
    lines.append("")

lines.append("---")
lines.append("")
lines.append("## Needs source — leads parked at C/D tier")
lines.append("")
lines.append("_(empty — no C/D-tier leads were promoted; agents discarded them)_")
lines.append("")

SOURCES_MD.write_text("\n".join(lines), encoding="utf-8")

# ---- Report ----
print("=== merge_batches.py report ===")
print()
print("Per-batch entry counts:")
total_in = 0
for name, n in per_batch_counts:
    print(f"  {name:55s} {n:>4}")
    total_in += n
print(f"  {'TOTAL READ':55s} {total_in:>4}")
print()
print(f"Unique entries in staging.json: {len(final)}")
print(f"Collisions (duplicate ids, kept first): {len(collisions)}")
for c in collisions:
    print(f"  ! {c}")
print()
print(f"Errors: {len(errors)}")
for er in errors:
    print(f"  X {er}")
print()
# Distribution
cat_counts = Counter(e["category"] for e in final)
conf_counts = Counter(e["_provenance"]["confidence"] for e in final)
print(f"Confidence distribution: A={conf_counts['A']}  B={conf_counts['B']}")
print()
print("Per-category counts:")
for cat in sorted(cat_counts):
    print(f"  {cat:20s} {cat_counts[cat]:>4}")

if errors:
    sys.exit(1)
